/**
 * Diccionario de traducción de nombres de equipos (inglés → español)
 *
 * Opción A (estática): cubre selecciones nacionales del Mundial 2026 y
 * variantes comunes de clubes que aparecen en torneos soportados.
 *
 * Uso: getTeamName(name) — siempre mostrar este valor en la UI;
 *   el valor original en inglés se sigue guardando en la base de datos.
 *
 * Opción B (automática por idioma del dispositivo via Intl.DisplayNames):
 *   planificada para V2.0 — ver arch/V2_0_PLAN.md sección 1.4.
 */

// ─── Selecciones nacionales ───────────────────────────────────────────────────
// Cubre los 48 equipos del Mundial 2026 + selecciones frecuentes en CL y ligas

const NOMBRES_ES: Record<string, string> = {
  // ── América del Norte y Central (CONCACAF) ────────────────────────────────
  'United States': 'Estados Unidos',
  'USA': 'Estados Unidos',
  'Mexico': 'México',
  'Canada': 'Canadá',
  'Panama': 'Panamá',
  'Costa Rica': 'Costa Rica',
  'Honduras': 'Honduras',
  'Jamaica': 'Jamaica',
  'El Salvador': 'El Salvador',
  'Guatemala': 'Guatemala',
  'Cuba': 'Cuba',
  'Trinidad and Tobago': 'Trinidad y Tobago',
  'Curacao': 'Curazao',
  'Guadaloupe': 'Guadalupe',
  'Haiti': 'Haití',
  'Nicaragua': 'Nicaragua',

  // ── América del Sur (CONMEBOL) ────────────────────────────────────────────
  'Brazil': 'Brasil',
  'Argentina': 'Argentina',
  'Colombia': 'Colombia',
  'Uruguay': 'Uruguay',
  'Chile': 'Chile',
  'Ecuador': 'Ecuador',
  'Peru': 'Perú',
  'Bolivia': 'Bolivia',
  'Paraguay': 'Paraguay',
  'Venezuela': 'Venezuela',

  // ── Europa (UEFA) ─────────────────────────────────────────────────────────
  'Spain': 'España',
  'France': 'Francia',
  'Germany': 'Alemania',
  'England': 'Inglaterra',
  'Portugal': 'Portugal',
  'Netherlands': 'Países Bajos',
  'Belgium': 'Bélgica',
  'Italy': 'Italia',
  'Croatia': 'Croacia',
  'Switzerland': 'Suiza',
  'Austria': 'Austria',
  'Denmark': 'Dinamarca',
  'Sweden': 'Suecia',
  'Norway': 'Noruega',
  'Finland': 'Finlandia',
  'Poland': 'Polonia',
  'Czech Republic': 'República Checa',
  'Czechia': 'República Checa',
  'Slovakia': 'Eslovaquia',
  'Hungary': 'Hungría',
  'Romania': 'Rumanía',
  'Bulgaria': 'Bulgaria',
  'Greece': 'Grecia',
  'Turkey': 'Türkiye',
  'Türkiye': 'Türkiye',
  'Ukraine': 'Ucrania',
  'Russia': 'Rusia',
  'Serbia': 'Serbia',
  'Slovenia': 'Eslovenia',
  'Albania': 'Albania',
  'Kosovo': 'Kosovo',
  'North Macedonia': 'Macedonia del Norte',
  'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
  'Montenegro': 'Montenegro',
  'Iceland': 'Islandia',
  'Scotland': 'Escocia',
  'Wales': 'Gales',
  'Ireland': 'Irlanda',
  'Republic of Ireland': 'República de Irlanda',
  'Northern Ireland': 'Irlanda del Norte',
  'Georgia': 'Georgia',
  'Azerbaijan': 'Azerbaiyán',
  'Armenia': 'Armenia',
  'Luxembourg': 'Luxemburgo',
  'Malta': 'Malta',
  'Cyprus': 'Chipre',
  'Estonia': 'Estonia',
  'Latvia': 'Letonia',
  'Lithuania': 'Lituania',
  'Belarus': 'Bielorrusia',
  'Moldova': 'Moldavia',
  'Andorra': 'Andorra',
  'Liechtenstein': 'Liechtenstein',
  'San Marino': 'San Marino',
  'Gibraltar': 'Gibraltar',

  // ── África (CAF) ──────────────────────────────────────────────────────────
  'Morocco': 'Marruecos',
  'Senegal': 'Senegal',
  'Cameroon': 'Camerún',
  'Nigeria': 'Nigeria',
  'Ghana': 'Ghana',
  'Egypt': 'Egipto',
  'Algeria': 'Argelia',
  'Tunisia': 'Túnez',
  "Ivory Coast": 'Costa de Marfil',
  "Côte d'Ivoire": 'Costa de Marfil',
  'South Africa': 'Sudáfrica',
  'DR Congo': 'Rep. Dem. del Congo',
  'Mali': 'Malí',
  'Burkina Faso': 'Burkina Faso',
  'Tanzania': 'Tanzania',
  'Angola': 'Angola',
  'Guinea': 'Guinea',
  'Uganda': 'Uganda',
  'Kenya': 'Kenia',
  'Ethiopia': 'Etiopía',
  'Zimbabwe': 'Zimbabue',
  'Zambia': 'Zambia',
  'Cape Verde': 'Cabo Verde',
  'Gabon': 'Gabón',
  'Mozambique': 'Mozambique',
  'Equatorial Guinea': 'Guinea Ecuatorial',
  'Comoros': 'Comoras',

  // ── Asia (AFC) ────────────────────────────────────────────────────────────
  'Japan': 'Japón',
  'South Korea': 'Corea del Sur',
  'Korea Republic': 'Corea del Sur',
  'Iran': 'Irán',
  'Saudi Arabia': 'Arabia Saudita',
  'Australia': 'Australia',
  'Qatar': 'Catar',
  'Iraq': 'Irak',
  'Jordan': 'Jordania',
  'Uzbekistan': 'Uzbekistán',
  'China': 'China',
  'China PR': 'China',
  'United Arab Emirates': 'Emiratos Árabes',
  'UAE': 'Emiratos Árabes',
  'Oman': 'Omán',
  'Kuwait': 'Kuwait',
  'Bahrain': 'Baréin',
  'Palestine': 'Palestina',
  'Indonesia': 'Indonesia',
  'Vietnam': 'Vietnam',
  'Thailand': 'Tailandia',
  'Philippines': 'Filipinas',
  'India': 'India',
  'Kyrgyzstan': 'Kirguistán',
  'Tajikistan': 'Tayikistán',

  // ── Oceanía (OFC) ─────────────────────────────────────────────────────────
  'New Zealand': 'Nueva Zelanda',
  'Fiji': 'Fiyi',
  'Papua New Guinea': 'Papúa Nueva Guinea',
  'Tahiti': 'Tahití',
  'Solomon Islands': 'Islas Salomón',

  // ─── Clubes — La Liga (España) ────────────────────────────────────────────
  'Real Madrid': 'Real Madrid',
  'FC Barcelona': 'Barcelona',
  'Barcelona': 'Barcelona',
  'Atletico Madrid': 'Atlético de Madrid',
  'Atlético de Madrid': 'Atlético de Madrid',
  'Athletic Club': 'Athletic de Bilbao',
  'Athletic Bilbao': 'Athletic de Bilbao',
  'Real Sociedad': 'Real Sociedad',
  'Villarreal': 'Villarreal',
  'Sevilla': 'Sevilla',
  'Sevilla FC': 'Sevilla',
  'Real Betis': 'Real Betis',
  'Valencia CF': 'Valencia',
  'Celta Vigo': 'Celta de Vigo',
  'Rayo Vallecano': 'Rayo Vallecano',
  'Getafe CF': 'Getafe',
  'Girona': 'Girona',
  'Osasuna': 'Osasuna',
  'Mallorca': 'Mallorca',
  'Alaves': 'Alavés',
  'Deportivo Alavés': 'Alavés',
  'Espanyol': 'Espanyol',
  'RCD Espanyol': 'Espanyol',
  'Granada CF': 'Granada',
  'UD Las Palmas': 'Las Palmas',
  'Leganes': 'Leganés',
  'CD Leganes': 'Leganés',
  'Valladolid': 'Valladolid',

  // ─── Clubes — Premier League (Inglaterra) ─────────────────────────────────
  'Manchester City': 'Manchester City',
  'Arsenal': 'Arsenal',
  'Chelsea': 'Chelsea',
  'Liverpool': 'Liverpool',
  'Manchester United': 'Manchester United',
  'Tottenham Hotspur': 'Tottenham',
  'Newcastle United': 'Newcastle',
  'Aston Villa': 'Aston Villa',
  'West Ham United': 'West Ham',
  'Everton': 'Everton',
  'Leicester City': 'Leicester',
  'Brighton & Hove Albion': 'Brighton',
  'Brighton': 'Brighton',
  'Wolverhampton Wanderers': 'Wolves',
  'Crystal Palace': 'Crystal Palace',
  'Nottingham Forest': 'Nottingham Forest',
  'Brentford': 'Brentford',
  'Fulham': 'Fulham',
  'AFC Bournemouth': 'Bournemouth',
  'Bournemouth': 'Bournemouth',
  'Ipswich Town': 'Ipswich',
  'Southampton': 'Southampton',
  'Luton Town': 'Luton',
  'Burnley': 'Burnley',
  'Sheffield United': 'Sheffield United',
  'Leeds United': 'Leeds',

  // ─── Clubes — Bundesliga (Alemania) ──────────────────────────────────────
  'Bayern Munich': 'Bayern Múnich',
  'FC Bayern Munich': 'Bayern Múnich',
  'Bayer Leverkusen': 'Leverkusen',
  'Borussia Dortmund': 'Borussia Dortmund',
  'RB Leipzig': 'RB Leipzig',
  'Eintracht Frankfurt': 'Eintracht Frankfurt',
  'VfB Stuttgart': 'Stuttgart',
  'SC Freiburg': 'Friburgo',
  'Wolfsburg': 'Wolfsburgo',
  'VfL Wolfsburg': 'Wolfsburgo',
  'Borussia Mönchengladbach': 'Borussia M\'gladbach',
  'Union Berlin': '1. FC Union Berlin',
  '1. FC Union Berlin': '1. FC Union Berlin',
  'Werder Bremen': 'Werder Bremen',
  'TSG 1899 Hoffenheim': 'Hoffenheim',
  'Augsburg': 'Augsburgo',
  'FC Augsburg': 'Augsburgo',
  'Mainz 05': 'Mainz',
  '1. FSV Mainz 05': 'Mainz',
  'Heidenheim': 'Heidenheim',
  'Darmstadt 98': 'Darmstadt',
  'Holstein Kiel': 'Holstein Kiel',
  'FC St. Pauli': 'St. Pauli',

  // ─── Clubes — Serie A (Italia) ────────────────────────────────────────────
  'Inter Milan': 'Inter de Milán',
  'Internazionale': 'Inter de Milán',
  'AC Milan': 'AC Milán',
  'Juventus': 'Juventus',
  'Napoli': 'Nápoles',
  'SSC Napoli': 'Nápoles',
  'AS Roma': 'AS Roma',
  'Roma': 'AS Roma',
  'Lazio': 'Lazio',
  'SS Lazio': 'Lazio',
  'Atalanta': 'Atalanta',
  'Fiorentina': 'Fiorentina',
  'ACF Fiorentina': 'Fiorentina',
  'Torino': 'Torino',
  'Bologna': 'Bolonia',
  'Bologna FC': 'Bolonia',
  'Udinese': 'Udinese',
  'Cagliari': 'Cagliari',
  'Lecce': 'Lecce',
  'Genoa': 'Génova',
  'Genoa CFC': 'Génova',
  'Hellas Verona': 'Hellas Verona',
  'Empoli': 'Empoli',
  'Monza': 'Monza',
  'Frosinone': 'Frosinone',
  'Salernitana': 'Salernitana',

  // ─── Clubes — Ligue 1 (Francia) ───────────────────────────────────────────
  'Paris Saint-Germain': 'PSG',
  'PSG': 'PSG',
  'Olympique de Marseille': 'Marsella',
  'Marseille': 'Marsella',
  'Olympique Lyonnais': 'Lyon',
  'Lyon': 'Lyon',
  'AS Monaco': 'Mónaco',
  'Monaco': 'Mónaco',
  'Lille OSC': 'Lille',
  'Lille': 'Lille',
  'RC Lens': 'Lens',
  'Stade Rennais': 'Rennes',
  'Rennes': 'Rennes',
  'OGC Nice': 'Niza',
  'Nice': 'Niza',
  'Nantes': 'Nantes',
  'FC Nantes': 'Nantes',
  'Brest': 'Brest',
  'Stade Brestois 29': 'Brest',
  'Toulouse FC': 'Toulouse',
  'Toulouse': 'Toulouse',
  'Strasbourg': 'Estrasburgo',
  'RC Strasbourg Alsace': 'Estrasburgo',
  'Montpellier': 'Montpellier',
  'Metz': 'Metz',
  'Clermont Foot': 'Clermont',

  // ─── Clubes — Eredivisie (Países Bajos) ───────────────────────────────────
  'Ajax': 'Ajax',
  'AFC Ajax': 'Ajax',
  'PSV Eindhoven': 'PSV',
  'PSV': 'PSV',
  'Feyenoord': 'Feyenoord',
  'AZ Alkmaar': 'AZ',
  'AZ': 'AZ',
  'FC Twente': 'Twente',

  // ─── Clubes — Primeira Liga (Portugal) ────────────────────────────────────
  'SL Benfica': 'Benfica',
  'Benfica': 'Benfica',
  'Sporting CP': 'Sporting de Portugal',
  'FC Porto': 'Oporto',
  'Porto': 'Oporto',
  'Braga': 'Braga',
  'SC Braga': 'Braga',

  // ─── Clubes — Copa del Rey ────────────────────────────────────────────────
  // (los clubes españoles ya están listados arriba)

  // ─── Términos genéricos de fase ───────────────────────────────────────────
  // (no son nombres de equipos, pero por si acaso)
};

/**
 * Retorna el nombre del equipo en español si existe en el diccionario.
 * Si no está, devuelve el nombre original (inglés u otro).
 *
 * @param name  Nombre original del equipo (tal como viene de football-data.org)
 * @returns     Nombre para mostrar en la UI
 */
export function getTeamName(name: string): string {
  if (!name) return name;
  return NOMBRES_ES[name] ?? name;
}
